services:
  - type: web
    name: violence-detection-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: 1
